# Taplo configuration
# https://taplo.tamasfe.dev/configuration/file.html

# Exclude patterns - respect .gitignore
exclude = [
  ".direnv/**",
  "target/**",
  "_*/**",
]

# Only include project TOML files
include = [
  "**/Cargo.toml",
  "rustfmt.toml"
]
